# Fastfood with Task Arithmetic Reconstruction - High Compression Test
# Tests regularization with aggressive compression (10% retention)
# This is NOT subspace merging - only reconstruction test

_target_: fusion_bench.method.FastfoodSubspaceMergeAlgorithm

# Task Arithmetic Reconstruction mode
use_task_arithmetic_reconstruction: true
task_arithmetic_scaling: 0.3
report_reconstruction_error: true

# Aggressive compression
proj_ratio: 0.1  # Compress to 10% (high compression)
use_G: true  # Use Gaussian scaling for better approximation
subspace_scope: "global"
block_rows: 8192

device: "cuda"

# Ignored in task arithmetic reconstruction mode
merge_where: "subspace"
merge_func: "sum"
weights: null
scale: 1.0
