# FastFood Wrapper Configuration for CausalLM Models
# Optimized for LLaMA-3.1 and similar causal language models

_target_: fusion_bench.method.FastfoodWrapperAlgorithm
_recursive_: false

# FastFood projection parameters
proj_ratio: 0.75                    # Projection ratio (0.0-1.0)
use_G: false                        # Use Gaussian scaling in FastFood transform
device: "cuda"                      # Computation device

# Subspace configuration
subspace_scope: "layer"             # Options: "per_tensor", "layer", "global"
block_rows: 8192                    # Memory efficiency parameter

# Wrapped merging method
merging_method: "simple_average"    # Method to apply in subspace
method_config:                      # Configuration for wrapped method
  # For task_arithmetic:
  # scaling_factor: 0.3
  
  # For ties_merging:  
  # scaling_factor: 0.3
  # threshold: 20.0
  # merge_func: "sum"
  
  # For fisher_merging:
  # normalize_fisher_weight: true
  # minimal_fisher_weight: 1e-6

# Performance profiling
enable_profiling: false
