# Fastfood with Task Arithmetic Reconstruction mode
# This config enables task arithmetic + projection to test regularization effects
# (NOT normal subspace merging - only reconstruction test)

_target_: fusion_bench.method.FastfoodSubspaceMergeAlgorithm

# Task Arithmetic Reconstruction mode
use_task_arithmetic_reconstruction: true
task_arithmetic_scaling: 0.3  # Standard TA scaling factor
report_reconstruction_error: true  # Report reconstruction error after projection

# Fastfood projection parameters
proj_ratio: 0.5  # Compress to 50% of original dimension
use_G: false  # Gaussian scaling (optional)
subspace_scope: "global"  # "global" | "layer" | "per_tensor"
block_rows: 8192

# Device
device: "cuda"

# These parameters are ignored in task arithmetic reconstruction mode
merge_where: "subspace"
merge_func: "sum"
weights: null
scale: 1.0
