# ============================================================================
# FastFood Regularization Configuration
# Test the effect of Fastfood projection on individual task models
# ============================================================================

_target_: fusion_bench.method.fastfood_regularize.FastfoodRegularizeAlgorithm

# ============================================================================
# Core FastFood Parameters
# ============================================================================
proj_ratio: 0.5               # Subspace compression ratio (0.0-1.0)
use_G: false                  # Use Gaussian scaling in FastFood transform
device: "cuda"                # Computation device
block_rows: 8192              # Memory management for large tensors
k_min: 64                     # Minimum projection dimension (protects tiny tensors)

# ============================================================================
# Subspace Configuration
# ============================================================================
subspace_scope: "per_tensor"      # per_tensor | layer | global

# ============================================================================
# Parameter Selection
# ============================================================================
exclude_parameters:           # fnmatch patterns to exclude from projection
  - "*norm*"                  # Layer normalization
  - "*bias*"                  # All biases
  - "*pos_embed*"             # Position embeddings
  - "*cls_token*"             # CLS token
  - "patch_embed.*"           # Patch embedding
  - "*running_*"              # Batch norm running statistics
  - "*num_batches_tracked*"   # Batch norm counters
