# ============================================================================
# FastFood Regularization Configuration
# Test the effect of Fastfood projection on individual task models
# ============================================================================

_target_: fusion_bench.method.fastfood_regularize.FastfoodRegularizeAlgorithm

# ============================================================================
# Core FastFood Parameters
# ============================================================================
proj_ratio: 0.75              # Subspace compression ratio (0.0-1.0)
use_G: false                  # Use Gaussian scaling in FastFood transform
device: "cuda"                # Computation device
block_rows: 16384             # Memory management for large tensors

# ============================================================================
# Subspace Configuration
# ============================================================================
subspace_scope: "global"     # per_tensor | per_flat_tensor | layer | global
                              # - per_tensor: row-wise projection (standard)
                              # - per_flat_tensor: flatten 2D to (out*in), one projection
                              # - layer: layer-wise shared projection
                              # - global: single global projection for all params

# ============================================================================
# TSV-Style Linear/Non-Linear Separation
# ============================================================================
only_project_linear: true    # If true, only 2D tensors are projected; 1D tensors merged with mean in original space
                              # This mimics TSV behavior: linear layers (weights) use subspace, non-linear (biases, norms) use mean

# ============================================================================