# Example FastFood configuration with TIES merging variants
# This demonstrates the new TIES aggregation options in FastFood merging

# ============================================================================
# FastFood Subspace Merging with TIES Configuration
# ============================================================================

_target_: fusion_bench.method.fastfood_merging.FastfoodSubspaceMergeAlgorithm

# ============================================================================
# Core FastFood Parameters
# ============================================================================
proj_ratio: 0.75              # Subspace compression ratio (0.0-1.0)
use_G: false                  # Use Gaussian scaling in FastFood transform
device: "cuda"                # Computation device
block_rows: 8192              # Memory management for large tensors

# ============================================================================
# Subspace Configuration
# ============================================================================
subspace_scope: "global"     # per_tensor | layer | global
merge_where: "subspace"       # subspace | postlift

# ============================================================================
# TIES Merging Strategy (NEW!)
# ============================================================================
merge_func: "ties_sum"        # Standard options: sum | mean | max | signmax | ema
                              # NEW TIES options: ties_sum | ties_mean | ties_max
                              
# TIES variants explanation:
# - ties_sum:  Elect majority sign per parameter, then sum agreeing task vectors
# - ties_mean: Elect majority sign per parameter, then mean of agreeing task vectors  
# - ties_max:  Elect majority sign per parameter, then max magnitude with correct sign
#
# Note: TIES implementation in FastFood skips the Trim phase (no parameter pruning)
# and focuses on Elect phase (sign resolution) + Disjoint Merge phase (selective aggregation)

align_mode: "none"            # none | ties | tadrop

# ============================================================================
# Advanced Alignment Options
# ============================================================================
ties_trim_pct: 0.0            # TIES pruning percentage (0.0-1.0) - NOT USED in FastFood TIES
tadrop_tau: 0.0               # Task Arithmetic dropout threshold

# ============================================================================
# Post-processing Options
# ============================================================================
use_pareto: false             # Apply Pareto frontier optimization
use_rescale: false            # Rescale merged parameters
weights: null                 # Task importance weights [w1, w2, ..., wN]
scale: 1.0                    # Global scaling factor

# ============================================================================
# Integrated Analysis Options
# ============================================================================
run_analysis: false          # Whether to run analysis after merging (disabled for SLURM workflow control)
analysis_methods: [merged_task_vector, task_vector_similarity, task_vector_layer]
analysis_output_path: null    # Path for analysis outputs (uses fabric logger if null)