# ============================================================================
# FastFood Regularization Configuration
# Test the effect of Fastfood projection on individual task models
# ============================================================================

_target_: fusion_bench.method.fastfood_regularize.FastfoodRegularizeAlgorithm

# ============================================================================
# Core FastFood Parameters
# ============================================================================
proj_ratio: 0.75              # Subspace compression ratio (0.0-1.0)
                              # e.g., 0.75 means m = 0.75 * D
transform_type: "srht"        # Transform type: "fwht" | "srht" | "dct" | "dht" | "none" | null
                              # Use "none" or null to skip projection entirely (baseline)
device: "cuda"                # Computation device (cuda or cpu)
block_rows: 16384              # Memory management: process matrices in blocks

# ============================================================================
# Subspace Configuration
# ============================================================================
subspace_scope: "per_tensor"  # per_tensor | layer | global
                              # - per_tensor: separate projection per parameter (recommended)
                              # - layer: shared projection within layer
                              # - global: single global projection for all params

# ============================================================================
# Filtering Options
# ============================================================================
only_project_linear: true     # If true, only project 2D weight matrices
                              # If false, project all floating point tensors (1D+)

# ============================================================================
# Post-processing Options
# ============================================================================
# energy_rescale removed - projection operators are assumed to be unitary

# ============================================================================