# ============================================================================
# Intrinsic Dimension and Task Diversity Analysis Configuration
# ============================================================================
# This configuration file defines parameters for analyzing:
# 1. Intrinsic Dimension: Per-task effective rank at each layer
# 2. Task Diversity: Cross-task covariance rank at each layer
#
# The effective rank is computed using entropy of normalized singular values:
#   effective_rank = exp(H(p)) where H(p) = -Σ p_i log(p_i)
#   and p_i = σ_i / Σ_j σ_j (normalized singular values)
# ============================================================================

_target_: fusion_bench.method.analysis.IntrinsicDimensionAnalysis

# ============================================================================
# Core Parameters
# ============================================================================
trainable_only: true          # Only analyze trainable parameters (recommended)
method_name: "intrinsic_dim"  # Name for output files
device: "cuda"                # Computation device

# ============================================================================
# Analysis Options
# ============================================================================
min_singular_value: 1.0e-6    # Threshold for filtering small singular values
save_detailed_results: true   # Save CSV files with per-layer results
create_plots: true            # Generate visualization plots

# ============================================================================
# Output Configuration
# ============================================================================
output_path: null             # Output directory (uses fabric logger if null)

# ============================================================================
# Expected Outputs
# ============================================================================
# 1. intrinsic_dimension_analysis_{method_name}.pdf
#    - Two-panel plot showing:
#      * Top: Mean effective rank per layer with error bars (intrinsic dimension)
#      * Bottom: Cross-task covariance effective rank per layer (task diversity)
#
# 2. intrinsic_dimension_results_{method_name}.csv
#    - Per-layer intrinsic dimension metrics:
#      * layer_index, mean_effective_rank, std_effective_rank,
#        min_effective_rank, max_effective_rank, num_tasks
#
# 3. task_diversity_results_{method_name}.csv
#    - Per-layer task diversity metrics:
#      * layer_index, covariance_effective_rank, num_tasks, num_parameters
#
# 4. analysis_summary_{method_name}.txt
#    - Human-readable summary with overall statistics
# ============================================================================
