# Learned Layer-wise FastFood Merging Configuration
_target_: fusion_bench.method.fastfood_merging.CLIPLearnedLayerWiseFastfoodMerging
name: learned_fastfood_layerwise

# FastFood basic configuration
proj_ratio: 0.5          # Default projection ratio (will be learned per-layer)
seed: 42
num_bases: null          # Auto-computed based on dimensions
normalize: true
normalization_type: "l2"
skip_normalization_if_matched: true
device: "cuda"

# Learned projection ratio configuration
proj_ratio_init_mode: "uniform"   # Options: uniform, inverse, forward, custom
proj_ratio_init_value: 0.5        # Initial value for projection ratios
learning_rate: 0.001              # Adam optimizer learning rate
num_epochs: 1                     # Number of training epochs
batch_size: 64                    # Batch size for test-time adaptation
entropy_weight: 1.0               # Weight for entropy loss term
min_proj_ratio: 0.1               # Minimum allowed projection ratio
max_proj_ratio: 1.0               # Maximum allowed projection ratio

# Training report configuration
training_report_dir: "/dss/dsshome1/08/di97hih/fusion_merging/training_reports"

# CLIP-specific configuration (for CLIP implementation)
clamp_weights: true
tie_weights: true
