# AdaFastFood Hybrid Merging Configuration  
# Combines AdaMerging adaptive coefficients with FastFood subspace projections
# Each layer learns optimal compression ratio + task mixing weights

_target_: fusion_bench.method.ada_fastfood_merging.CLIPAdaFastFoodMergingAlgorithm

# ============================================================================
# Projection Parameters (FastFood subspace)
# ============================================================================
proj_init_strategy: "conservative"  # "conservative" | "layer_dependent" | "uniform"
proj_init_value: 0.3               # Initial projection ratio (30% compression)
proj_lr: 1e-3                      # Learning rate for projection parameters
use_G: false                       # Use Gaussian scaling in FastFood transform
clamp_proj: true                   # Clamp projection ratios to [0.1, 1.0]

# ============================================================================
# AdaMerging Parameters (task mixing coefficients)
# ============================================================================
ada_init_value: null               # Initial AdaMerging weights (null = 1/num_tasks)
ada_lr: 1e-3                       # Learning rate for AdaMerging weights
clamp_weights: true                # Clamp AdaMerging weights to [0, 2]

# ============================================================================
# Training Parameters
# ============================================================================
optimizer: adam                    # Optimizer type
lr: 1e-3                          # Default learning rate (if proj_lr/ada_lr not set)
max_steps: 1000                    # Test-time adaptation steps
fast_dev_run: ${fast_dev_run}      # Quick debug run
batch_size: 16                     # Batch size for test data
num_workers: 8                     # DataLoader workers

# ============================================================================
# Model Parameters
# ============================================================================
tie_weights: true                  # Pass to functional_call
strict: false                     # Pass to functional_call
device: "cuda"                     # Computation device

# ============================================================================
# Saving and Logging
# ============================================================================
save_merging_weights: 'ada_fastfood_weights.pt'  # Path to save learned parameters
cache_dir: outputs                 # Cache directory

# ============================================================================
# FastFood Configuration  
# ============================================================================
subspace_scope: "layer"           # "layer" | "global" | "per_tensor" (layer recommended for AdaMerging)
block_rows: 8192                   # Block size for memory management

# ============================================================================
# CLIP-specific settings
# ============================================================================
exclude_classification_head: true
vision_encoder_only: true

# ============================================================================
# Visualization and Analysis
# ============================================================================
plot_learned_params: true             # Generate visualization of learned parameters
plot_save_path: "ada_fastfood_params_analysis.png"  # Path to save plots

# ============================================================================
# Test datasets (configure per experiment)
# ============================================================================
test_datasets: {}
# warmup_steps: 100                # Warmup steps before full optimization
# projection_regularization: 0.0   # L2 regularization on projection params