# ============================================================================
# FastFood Wrapper - Task Singular Vector Merging Configuration
# Projects to subspace, applies native TSVM algorithm, lifts back
# Full TSVM: SVD on task vectors + reconstruction in projected space
# ============================================================================

_target_: fusion_bench.method.fastfood_wrapper.FastfoodWrapperAlgorithm

# Core FastFood projection parameters
proj_ratio: 0.75              # Compression ratio (0.0-1.0)  
use_G: false                  # Use Gaussian scaling in FastFood
device: "cuda"                # Computation device
subspace_scope: "layer"       # per_tensor | layer | global

# Merging configuration
merging_method: "task_singular_vector"
method_config:
  alpha: 1                    # Alpha parameter for TSVM
  exclude_keys: null          # Keys to exclude
  return_single_task_models: false  # Return individual models
