# TA2 Vision Subset: MNIST + EuroSAT (CLIP ViT-Base Patch16)  
# Simple digits + Satellite imagery with higher resolution
defaults:
  - /dataset/image_classification/train@train_datasets:
      - mnist
      - eurosat
  - /dataset/image_classification/test@test_datasets:
      - mnist
      - eurosat
  - _self_
_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False
processor: openai/clip-vit-base-patch16
models:
  _pretrained_: openai/clip-vit-base-patch16
  mnist: tanganke/clip-vit-base-patch16_mnist
  eurosat: tanganke/clip-vit-base-patch16_eurosat
platform: hf
