# Config for GTSRB, MNIST, SVHN image classification tasks
defaults:
  - /dataset/image_classification/train@train_datasets:
      - gtsrb
      - mnist
      - svhn
  - /dataset/image_classification/test@test_datasets:
      - gtsrb
      - mnist
      - svhn
  - _self_
_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False
processor: openai/clip-vit-base-patch32
models:
  _pretrained_: openai/clip-vit-base-patch32
  gtsrb: tanganke/clip-vit-base-patch32_gtsrb
  mnist: tanganke/clip-vit-base-patch32_mnist
  svhn: tanganke/clip-vit-base-patch32_svhn
platform: hf
