# Learnable Fastfood Merging for CLIP models
# This method learns optimal projection ratios for each layer during test-time adaptation

name: clip_learnable_fastfood_merging

# ============ Learning Parameters ============
# Initial projection ratio for all layers (will be optimized)
init_proj_ratio: 0.1
# Learning rate for optimization
lr: 0.01
# Optimizer type (currently only 'adam' supported)
optimizer: adam
# Number of optimization steps
max_steps: 500
# Batch size for test data
batch_size: 16
# Number of data loading workers
num_workers: 8

# ============ Projection Ratio Constraints ============
# Whether to clamp projection ratios to valid range
clamp_ratios: true
# Minimum allowed projection ratio
min_proj_ratio: 0.01
# Maximum allowed projection ratio
max_proj_ratio: 1.0

# ============ Fastfood Merging Parameters (Fixed) ============
# Aggregation function in subspace
merge_func: sum  # Options: sum, mean, ties_sum, ties_mean, ema
# Whether to use Gaussian scaling in Fastfood transform
use_G: false
# Device for computation
device: cuda
# Block size for processing (memory optimization)
block_rows: 8192
# Task weights for merging (null = uniform weights)
weights: null
# Post-merge scaling factor
scale: 1.0

# ============ Output and Caching ============
# Path to save learned projection ratios (optional)
save_projection_ratios: "learned_projection_ratios.pt"
# Cache directory for zero-shot weights
cache_dir: outputs/cache

# ============ Debug Options ============
fast_dev_run: ${fast_dev_run}
